# 3層ニューラルネットワークの実装

![graph](../files/nn_3.png)

- 入力層(第0層)は２つ
- １つ目の隠れ層(第1層)は3つ
- 2つ目の隠れ層(第2層)は2つ
- 出力層(第3層)は2つ

![1](../files/nn_3_1.png)

- 定数1のバイアスを追加

### $a_1^{(1)}$ の数式

$
a_1^{(1)} = w_{11}^{(1)}x_1 + w_{12}^{(1)}x2 + b_1
$

行列の内積を用いると第１層は次の式でまとめて表示できる

$
{\bf A}^{(1)}= {\bf XW}^{(1)} + {\bf B}
$

In [2]:
import numpy as np

第1層の実装
---

In [3]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])
print(X.shape)
print(W1.shape)
print(B1.shape)
print(W1)

(2,)
(2, 3)
(3,)
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]]


In [4]:
# 行列の内積を使って第1層への入力を作る
A1 = np.dot(X, W1) + B1
print(A1)

[0.3 0.7 1.1]


In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
# 第1層の入力を活性化関数に通す(シグモイド関数)
Z1 = sigmoid(A1)
print(Z1)

[0.57444252 0.66818777 0.75026011]


第2層の実装
---

In [9]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [11]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
print(Z2)

[0.62624937 0.7710107 ]


第2層から出力層へ
---


In [12]:
def identity_function(x):
    return x

In [15]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
print(Y)

[0.31682708 0.69627909]


- identity_functionは 「恒等関数」と言われるもので入力をそのまま出力する