参考
----------
* [ベクトルの内積や行列の積を求めるnumpy.dot関数の使い方](https://deepage.net/features/numpy-dot.html)

### ベクトルの内積(dot)
* ベクトルの内積とは各要素の積を全て足し合わせたもの
* あるベクトルa([1, 2, 3])とベクトルb([2, 3, 4])があった場合は以下になる
* `(a[0] * b [0]) + (a[1] * b [1]) + (a[2] * b [2])` = `(1 * 2) + (2 * 3) + (3 * 4)` = 20

In [2]:
import numpy as np

a = [1,2,3]
b = [2,3,4]

np.dot(a, b)

20

### 行列の内積(dot)
* 左側の行と右側の列の要素の積を足し合わせる
* ある行列a[[1,2,3]]、ある行列b=[[2],[3],[4]]があった場合は以下となる
* (a[0][0] * b[0][0]) +  (a[0][1] * b[1][0]) + (a[0][1] * b[1][0]) + (a[0][2] * b[2][0]) = `(1 * 2) + (2 * 3) + (3 * 4)` = [[20]]
* 左側の行列(上でいうと行列a)の列数と右側(上でいうと行列b)の行列の行数が合っていないとエラーになる

In [16]:
import numpy as np

a = [[1, 2, 3]]
b = [
    [2],
    [3],
    [4]
 ]

np.dot(a, b)

array([[20]])

In [20]:
import numpy as np

a = [[1, 2, 3], [1, 2, 3]]
b = [
    [2],
    [3],
    [4]
 ]

np.dot(a, b)

array([[20],
       [20]])

Exp 指数関数
----------------
* numpy.exp(x) は e の x 乗を返す
* eは、自然対数の底(大体2.7位)

In [1]:
import numpy as np

a = [2, 3, 4]
np.exp(a)

array([  7.3890561 ,  20.08553692,  54.59815003])

In [ ]:
log 対数関数
--------------------
* numpy.log(x) は、　

linspace
--------------------

* 等差数列を生成する関数

clip
-------------
* 範囲内に値を収めることができる