参考
----------
* [ベクトルの内積や行列の積を求めるnumpy.dot関数の使い方](https://deepage.net/features/numpy-dot.html)

### ベクトルの内積(dot)
* ベクトルの内積とは各要素の積を全て足し合わせたもの
* あるベクトルa([1, 2, 3])とベクトルb([2, 3, 4])があった場合は以下になる
* `(a[0] * b [0]) + (a[1] * b [1]) + (a[2] * b [2])` = `(1 * 2) + (2 * 3) + (3 * 4)` = 20

In [2]:
import numpy as np

a = [1,2,3]
b = [2,3,4]

np.dot(a, b)

20

### 行列の内積(dot)
* 左側の行と右側の列の要素の積を足し合わせる
* ある行列a[[1,2,3]]、ある行列b=[[2],[3],[4]]があった場合は以下となる
* (a[0][0] * b[0][0]) +  (a[0][1] * b[1][0]) + (a[0][1] * b[1][0]) + (a[0][2] * b[2][0]) = `(1 * 2) + (2 * 3) + (3 * 4)` = [[20]]
* 左側の行列(上でいうと行列a)の列数と右側(上でいうと行列b)の行列の行数が合っていないとエラーになる

In [16]:
import numpy as np

a = [[1, 2, 3]]
b = [
    [2],
    [3],
    [4]
 ]

np.dot(a, b)

array([[20]])

In [20]:
import numpy as np

a = [[1, 2, 3], [1, 2, 3]]
b = [
    [2],
    [3],
    [4]
 ]

np.dot(a, b)

array([[20],
       [20]])

Exp 指数関数
----------------
* numpy.exp(x) は e の x 乗を返す
* eは、自然対数の底(大体2.7位)

In [1]:
import numpy as np

a = [2, 3, 4]
np.exp(a)

array([  7.3890561 ,  20.08553692,  54.59815003])

In [ ]:
log 対数関数
--------------------
* numpy.log(x) は、　

## linspace
--------------------

* 等差数列を生成する関数

In [3]:
import numpy as np
# 0 から 1まで200個
x = np.linspace(0, 1, 200)
print(x)

[ 0.          0.00502513  0.01005025  0.01507538  0.0201005   0.02512563
  0.03015075  0.03517588  0.04020101  0.04522613  0.05025126  0.05527638
  0.06030151  0.06532663  0.07035176  0.07537688  0.08040201  0.08542714
  0.09045226  0.09547739  0.10050251  0.10552764  0.11055276  0.11557789
  0.12060302  0.12562814  0.13065327  0.13567839  0.14070352  0.14572864
  0.15075377  0.15577889  0.16080402  0.16582915  0.17085427  0.1758794
  0.18090452  0.18592965  0.19095477  0.1959799   0.20100503  0.20603015
  0.21105528  0.2160804   0.22110553  0.22613065  0.23115578  0.2361809
  0.24120603  0.24623116  0.25125628  0.25628141  0.26130653  0.26633166
  0.27135678  0.27638191  0.28140704  0.28643216  0.29145729  0.29648241
  0.30150754  0.30653266  0.31155779  0.31658291  0.32160804  0.32663317
  0.33165829  0.33668342  0.34170854  0.34673367  0.35175879  0.35678392
  0.36180905  0.36683417  0.3718593   0.37688442  0.38190955  0.38693467
  0.3919598   0.39698492  0.40201005  0.40703518  0.4

clip
-------------
* 範囲内に値を収めることができる