In [1]:
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

# ソフトマックス関数 

$ \displaystyle y_k = \frac{\displaystyle exp({a_k})}{ \displaystyle\sum_{i=1}^n exp({a_i})}$

特徴
---
- 出力は0から1.0の間の実数になる
- 出力の総和は1になる

In [10]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a) # 指数関数
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [11]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [12]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [14]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # オーバーフロー対策でMax値を引く
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [17]:
res = softmax(np.array([1010, 1000, 990]))
print(res)
print(np.sum(res))

[9.99954600e-01 4.53978686e-05 2.06106005e-09]
1.0
