In [8]:
import numpy as np

勾配
---

- すべての変数の偏微分をベクトルとしてまとめたものを `勾配(gradient)` という 

In [9]:
# 例題関数
def function_2(x):
    return x[0]**2 + x[1]**2

In [10]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x) # xと同じ形状で0初期化された配列
    
    for idx in range(x.size):
        tmp_val = x[idx]
        # f(x + h)の計算
        x[idx] = tmp_val + h
        fx1 = f(x)
        
        # f(x - h)の計算
        x[idx] = tmp_val - h
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2*h)
        x[idx] = tmp_val
    return grad

In [11]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [12]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [13]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])

# 勾配降下法

$ x_0 = x_0 - \eta\frac{df}{dx_0} $

$ x_1 = x_1 - \eta\frac{df}{dx_1} $

In [15]:
def gradient_descent(f, init_x, lr=0.001, step_num=100):
    """
    lr: learning rate
    """
    x = init_x
    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad
    return x

In [16]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])