勾配
---

- すべての変数の偏微分をベクトルとしてまとめたものを `勾配(gradient)` という 

In [3]:
import numpy as np

In [4]:
# 例題関数
def function_2(x):
    return x[0]**2 + x[1]**2

In [5]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x) # xと同じ形状で0初期化された配列
    
    for idx in range(x.size):
        tmp_val = x[idx]
        # f(x + h)の計算
        x[idx] = tmp_val + h
        fx1 = f(x)
        
        # f(x - h)の計算
        x[idx] = tmp_val - h
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2*h)
        x[idx] = tmp_val
    return grad

In [7]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [8]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [9]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])