# 四則演算

In [5]:
println(1 + 2 * 3)
println(5/2)
println(div(5, 2)) # 正数の割り算
println(2^10) # べき乗

7
2.5
2
1024


# 変数代入

In [6]:
α = 5 # 英数字以外も使える \から始まる LateX表記をタブで保管できる

5

# if

In [7]:
if 1 < 2
    print(1)
else
    print(2)
end
   
i = 2
if i == 1
   print(1)
elseif i == 2
   print(2)
else
   print("other")
end

12

# for

In [8]:
for n in 1:3
    println(n)
end

# =とinは同じ
for n = 1:3
    println(n)
end

1
2
3
1
2
3


# 文字列

In [9]:
str = "Julia Language" # 文字列はダブルクオート(")
c = 'c' # シングルクオートだとリテラルになる

'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

# 正規表現

In [10]:
str = "Julia Language"
m = match(r"L.*(.)$", str) # 正規表現のパターンはr"<文字列>"
println(m.captures)
replace(str, r"\sL.*$" => "言語") # 正規表現の文字列置換

Union{Nothing, SubString{String}}["e"]


"Julia言語"

# 配列の生成とアクセス

In [11]:
xs = [1, 2, 3]
println(xs[1]) # 配列の添字は1から始まる
println(xs[1:2])
println(xs[2:end])
xs[1:2] = [10, 20]
println(xs)
xs[2:end] .= 5 # スカラ値で範囲を上書きする(ブロードキャスト演算子)
println(xs)

1
[1, 2]
[2, 3]
[10, 20, 3]
[10, 5, 5]


# 多次元配列(行列、テンソル)

In [12]:
col = [1.0, 2.0] # 列は1次元配列と同じ
println(col)
row = [1.0 2.0] # 行はカンマではなく空白区切りで表現する
println(row)
A = [1.0 3.0; 2.0 4.0] # 行列は空白区切りの要素をセミコロンもしくは改行で区切る
A = [1.0 3.0
    2.0 4.0] # 改行でも同じ
println(A[1, 2]) # 1行目の2列目
println(A[end, 2]) # 2行目の2列目

[1.0, 2.0]
[1.0 2.0]
3.0
4.0


# 行列演算 

In [13]:
println(row * col) # 行列積の計算
println(col * row) # 列 * 行
println(row * A * col) # 行 * 行列 * 列
println(col') # エルミート共役

[5.0]
[1.0 2.0; 2.0 4.0]
[27.0]
[1.0 2.0]


In [22]:
# 要素が初期化されていない配列2*2*1
Array{Float64}(undef, 2, 2, 1)

2×2×1 Array{Float64,3}:
[:, :, 1] =
 6.94857e-310  6.94856e-310
 6.94857e-310  6.94856e-310

In [23]:
# ゼロ初期化した配列
zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [25]:
# 1初期化した配列
ones(Int, 1, 3)

1×3 Array{Int64,2}:
 1  1  1

In [26]:
# reshapeはメモリ配置が同じでサイズの異なる配列を生成する
# 1~6を２行3列
reshape(1:6, 2, 3)

2×3 reshape(::UnitRange{Int64}, 2, 3) with eltype Int64:
 1  3  5
 2  4  6

In [27]:
# 1~6を1行
reshape(1:6, 1, :)

1×6 reshape(::UnitRange{Int64}, 1, 6) with eltype Int64:
 1  2  3  4  5  6

# ドット演算とブロードキャスト

In [28]:
[1, 2] .* [1, 10]

2-element Array{Int64,1}:
  1
 20

In [29]:
sin.([0.0, pi/2])

2-element Array{Float64,1}:
 0.0
 1.0

In [30]:
# 配列の大きさが一致しない場合は小さい方を適当に拡大して合わせる(ブロードキャスト)
[1 2] .* [1, 10]

2×2 Array{Int64,2}:
  1   2
 10  20

In [38]:
# ドット演算が連続すると自動的に1つのループにまとめられる(fused expression)
X = randn(100_00)
Y = zeros(length(X))
Y += X; Y .+= X;
# @timeマクロは実行時間と割当メモリの測定
@time Y += X;
@time Y.+= X; # ドット演算を使ったほうがパフォーマンスがいい
@time @. Y+= X;

  0.000571 seconds (6 allocations: 78.359 KiB)
  0.000390 seconds (6 allocations: 208 bytes)
  0.000075 seconds (6 allocations: 208 bytes)


# 辞書の生成

In [39]:
d = Dict("apple" => "red", "banana" => "yellow")

Dict{String,String} with 2 entries:
  "banana" => "yellow"
  "apple"  => "red"

In [47]:
println(d["apple"])
println(haskey(d, "apple")) # keyの存在確認
println(haskey(d, "peach"))
println(get(d, "peach", "pink")) # getを使うとキーが存在しなときにデフォルト値が設定できる
d["peach"] = "pink" # 代入
println(haskey(d, "peach"))

red
true
true
pink
true


# 統計処理

In [14]:
using Statistics

In [50]:
xs = [1, 2, 3, 10, 20, 30, 100, 200, 300]
println(mean(xs)) # 平均
println(var(xs)) # 不偏分散
println(var(xs, corrected=false)) # 分散

74.0
11516.25
10236.666666666666


In [52]:
# 行列計算
A = reshape(xs, 3, 3)
println(mean(A))

74.0


# 具象型

In [60]:
println(typeof(1))
println(typeof(1.5))
println(typeof('a'))
println(typeof("str"))

Int64
Float64
Char
String


# ユーザー定義型 

In [65]:
struct T
    x::Int # フィールドは name::Typeの形式で宣言する
end
t = T(42)
println(t.x)
# structで作成した型はimmutableのためフィールドの値は変更できない
t.x = 10

42


ErrorException: setfield! immutable struct of type T cannot be changed

# 具象型
- 各型の間には何らかの近さを持つ
- すべての方はAnyを単一のルートにもつ1つの巨大な木構造になっている

In [69]:
# abstruct type <Name> end で抽象型を定義できる
abstract type MyInteger <: Integer end
# <: でスーパータイプを指定できる
struct MyInt <: MyInteger
    x::Int
end

# 型ユニオン
- 型をグループ化することができる

In [4]:
U = Union{Int, String}
println(isa("Foo", U))
println(isa(1, U))

true
true


# パラメトリック型
- 型はパラメタを持てる

In [8]:
struct Point{T<:Real} 
    x::T
end
println(Point(1)) # 型推論
println(Point{Float64}(1.5)) # 型を明示
println(Point("Str")) # StringはRealではないためエラー

Point{Int64}(1)
Point{Float64}(1.5)


MethodError: MethodError: no method matching Point(::String)
Closest candidates are:
  Point(!Matched::T<:Real) where T<:Real at In[8]:2

# 関数
- function Name(ARGS)
- Name(ARGS)
で関数を定義できる

In [10]:
double(x) = 2x # リテラルと変数を連続で記載すると乗算になる

double (generic function with 1 method)

In [20]:
# ARG=VALUEでデフォルト引数を定義できる
# ;より後ろに書いた引数はすべてキーワード引数となる
function add(x; y=1)
    return x+y
end
println(add(3))
println(add(3, y=5))

4
8


In [21]:
swap(x, y) = (y, x) # () を使うとタプルで複数の値を返せる

swap (generic function with 1 method)

In [23]:
(x, y) = swap(1, 2) # タプルを使って複数の変数にバインドできる

(2, 1)

多重ディスパッチ
---

In [25]:
foo(x::Int) = 42 # 引数に型を指定できる

foo (generic function with 1 method)

In [26]:
foo(x::Float64) = 3.14

foo (generic function with 2 methods)

In [32]:
foo(x) = 100

foo (generic function with 3 methods)

In [35]:
# 引数の型判定を行いもっとも一致するメソッドが呼ばれる
println(foo(1))
println(foo(1.5))
println(foo("str"))

42
3.14
100


無名関数
---

In [39]:
println((n->n+1)(1))
f = n->n+1

2


#19 (generic function with 1 method)

In [40]:
f(1)

2

In [41]:
((x, y)->x+y)(1, 2)

3

In [42]:
(()->42)()

42

関数を引数に取る関数とdo構文
---

In [43]:
map(d->d+1, [1, 2, 3]) # mapは第一引数に関数を受け取る

3-element Array{Int64,1}:
 2
 3
 4

In [48]:
# 上記のシンタックスシュガーとしてdo構文が使える
map([1,2,3]) do d
    d+1
end

3-element Array{Int64,1}:
 2
 3
 4

In [54]:
sym = :x
ex = :(x+1)
eval(ex)
eval(sym)

10

In [56]:
run(`ls`)

files
hogw.csv
Julia基本.ipynb
material.csv
new.csv
not_popular.csv
old.csv
platypus.ipynb
res.json
sql2.csv
sql.csv
Untitled.ipynb
ナップザック問題.ipynb
焼き肉最適化問題.ipynb


Process(`ls`, ProcessExited(0))