# 多次元配列の計算

1次元
---

In [2]:
import numpy as np

# 配列の作成
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [4]:
# 次元数の取得
np.ndim(A)

1

In [6]:
# 形状の取得
A.shape

(4,)

２次元
---

In [9]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
np.ndim(B)

2

In [12]:
B.shape

(3, 2)

行列の内積
---
![dot](../files/dot.png)

In [13]:
A = np.array([[1, 2], [3, 4]])

In [14]:
A.shape

(2, 2)

In [16]:
B = np.array([[5, 6], [7, 8]])

In [18]:
B.shape

(2, 2)

In [20]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

---

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [22]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [23]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

- Aの列数とBの行数は同じでなければならない